name: MLflow CI Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install mlflow==2.19.0 pandas scikit-learn

      - name: Train Model
        working-directory: ./MLProject
        run: mlflow run . --env-manager local

      - name: Upload Artifact to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: trained-model-artifacts
          path: ./MLProject/mlruns/

      - name: Prepare Model Artifact for Docker
        working-directory: ./MLProject
        run: |
          # Ambil path model dari file text, lalu copy ke folder model_artifact biar gampang dibuild
          MODEL_PATH=$(cat model_path.txt)
          cp -r "$MODEL_PATH" ./model_artifact

      - name: Build and Push Docker Image
        working-directory: ./MLProject
        run: |
          # Login ke Docker Hub
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          # Build image pakai Dockerfile buatan kita
          docker build -t ${{ secrets.DOCKER_USERNAME }}/network-flow-model:latest .
          # Push ke Docker Hub
          docker push ${{ secrets.DOCKER_USERNAME }}/network-flow-model:latest